name: Upload Ali OSS

on:
  workflow_call:
    secrets:
      key-id:
        required: true
      key-secret:
        required: true
        
    inputs:
      region: 
        required: true
        type: string
      bucket: 
        required: true
        type: string
      oss-path:
        required: true
        type: string
        
jobs:
  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          name: build-dist-artifact
          path: build

      - name: Upload to oss
        id: upload_to_oss
        uses: tvrcgo/upload-to-oss@master
        with:
          key-id: ${{ inputs.key-id }}
          key-secret: ${{ inputs.key-secret }}
          region: ${{ inputs.region }}
          bucket: ${{ inputs.bucket }}
          assets: |
            build/**:${{ inputs.oss-path }}